services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .env.docker:/var/www/.env
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - QUEUE_CONNECTION=redis
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - database
    entrypoint: >
      sh -c "./wait-for-it.sh database:3306 -- php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

  database:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue-worker
    working_dir: /var/www
    entrypoint: >
      sh -c "./wait-for-it.sh app:8000 -- php artisan queue:work --tries=3 --timeout=60"
    volumes:
      - .:/var/www
    depends_on:
      - database
      - app

volumes:
  db_data:
